# Funding information for Vibe Coder MCP
# This helps GitHub show sponsor buttons and package information

# GitHub Sponsors
github: freshtechbro

# NPM Package Link
custom: ["https://www.npmjs.com/package/vibe-coder-mcp"]

# Other funding platforms can be added here
# patreon: username
# ko_fi: username
