# Funding information for Vibe Coder MCP
# This helps GitHub show sponsor buttons and package information

# GitHub Sponsors
github: freshtechbro

# Other funding platforms can be added here
# patreon: username
# ko_fi: username
# custom: https://your-funding-link.com