// src/tools/rules-generator/tests/index.test.ts
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generateRules } from '../index.js';
import { OpenRouterConfig } from '../../../types/workflow.js';
import * as researchHelper from '../../../utils/researchHelper.js';
import * as sequentialThinking from '../../sequential-thinking.js';
import fs from 'fs-extra';

// Mock dependencies
vi.mock('../../../utils/researchHelper.js');
vi.mock('../../sequential-thinking.js');
vi.mock('fs-extra');

describe('Rules Generator', () => {
  // Mock data and responses
  const mockConfig: OpenRouterConfig = {
    baseUrl: 'https://api.example.com',
    apiKey: 'test-api-key',
    geminiModel: 'google/gemini-2.5-pro-exp-03-25:free', 
    perplexityModel: 'perplexity/sonar-deep-research'
  };
  
  const mockUserStories = 'US-001: As a user, I want to...';
  const mockRuleCategories = ['Code Style', 'Architecture', 'Security'];
  
  const mockResearchResults = [
    "Mock best practices research data",
    "Mock rule categories research data",
    "Mock architecture patterns research data"
  ];

  const mockGeneratedRules = "# Mock Rules\n\nThis is a mock rules document generated by the test.";

  beforeEach(() => {
    // Clear all mocks before each test
    vi.clearAllMocks();
    
    // Mock initDirectories to avoid file system operations
    vi.spyOn(fs, 'ensureDir').mockResolvedValue();
    vi.spyOn(fs, 'writeFile').mockResolvedValue();
    
    // Mock the Promise.allSettled for research results
    vi.spyOn(Promise, 'allSettled').mockResolvedValue([
      { status: 'fulfilled', value: mockResearchResults[0] },
      { status: 'fulfilled', value: mockResearchResults[1] },
      { status: 'fulfilled', value: mockResearchResults[2] }
    ]);
    
    // Mock the performResearchQuery function
    vi.spyOn(researchHelper, 'performResearchQuery')
      .mockImplementation(async (query: string) => {
        // Return different results based on the query
        if (query.includes('practices')) return mockResearchResults[0];
        if (query.includes('categories')) return mockResearchResults[1];
        if (query.includes('architecture')) return mockResearchResults[2];
        return "Default mock research";
      });
    
    // Mock the processWithSequentialThinking function
    vi.spyOn(sequentialThinking, 'processWithSequentialThinking')
      .mockResolvedValue(mockGeneratedRules);
  });

  it('should perform research (Perplexity) then generation (Gemini) with research context', async () => {
    // Test input with params object matching new function signature
    const params = {
      productDescription: "A test product description",
      userStories: mockUserStories,
      ruleCategories: mockRuleCategories
    };
    
    // Call the function under test
    await generateRules(params, mockConfig);
    
    // Verify Perplexity research was called 3 times (for 3 different queries)
    expect(researchHelper.performResearchQuery).toHaveBeenCalledTimes(3);
    
    // Verify each research query contains appropriate context and uses the correct config
    const researchCalls = vi.mocked(researchHelper.performResearchQuery).mock.calls;
    expect(researchCalls[0][0]).toContain('practices');
    expect(researchCalls[0][1]).toBe(mockConfig); // Should pass full config with perplexityModel
    expect(researchCalls[1][0]).toContain('categories');
    expect(researchCalls[2][0]).toContain('architecture');
    
    // Verify Gemini generation was called exactly once
    expect(sequentialThinking.processWithSequentialThinking).toHaveBeenCalledTimes(1);
    
    // Get the generation prompt and verify it contains all inputs and research context
    const generationPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][0];
    expect(generationPrompt).toContain(params.productDescription);
    expect(generationPrompt).toContain(params.userStories);
    expect(generationPrompt).toContain("Pre-Generation Research Context");
    
    // Verify the config was correctly passed to processWithSequentialThinking
    const passedConfig = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][1];
    expect(passedConfig).toBe(mockConfig); // Should pass full config with geminiModel
    
    // Verify the system prompt was passed to guide Gemini in using research context
    const systemPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][2];
    expect(systemPrompt).toContain("Rules Generator");
    expect(systemPrompt).toContain("Using Research Context");
    
    // Verify results are written to file
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
  });

  it('should handle custom rule categories in the research process', async () => {
    // Call with specific rule categories using params object
    const params = {
      productDescription: "Test product",
      ruleCategories: ["Security", "Performance"]
    };
    await generateRules(params, mockConfig);
    
    // Verify the second research query uses the provided categories
    const secondResearchQuery = vi.mocked(researchHelper.performResearchQuery).mock.calls[1][0];
    expect(secondResearchQuery).toContain("Security, Performance");
  });

  it('should handle research failures gracefully', async () => {
    // Mock a failed research query
    vi.mocked(Promise.allSettled).mockResolvedValueOnce([
      { status: 'rejected', reason: new Error('Research failed') },
      { status: 'fulfilled', value: mockResearchResults[1] },
      { status: 'fulfilled', value: mockResearchResults[2] }
    ]);
    
    const params = {
      productDescription: "A test product description",
      userStories: mockUserStories,
      ruleCategories: mockRuleCategories
    };
    await generateRules(params, mockConfig);
    
    // Verify Gemini generation was still called
    expect(sequentialThinking.processWithSequentialThinking).toHaveBeenCalledTimes(1);
    
    // Verify the prompt contains an error message for the failed research
    const generationPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][0];
    expect(generationPrompt).toContain("*Research on this topic failed*");
    
    // Verify results are still written to file
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
  });

  // --- Snapshot Test ---
  it('should generate rules content matching snapshot', async () => {
    const productDescription = "A sample product for snapshot";
    const userStories = "US-001: As a user, I want consistent rules"; 
    const ruleCategories = ["Code Style", "Architecture", "Security"];
    const consistentMockRules = "# Coding Rules\n\n## Code Style\n\n1. Rule description...\n\n## Architecture\n\n1. Rule description...\n\n## Security\n\n1. Rule description...";
    
    // Variable to capture the file path argument directly
    let capturedFilePath: string = '';
    
    // Reset mocks with consistent values for snapshot stability
    vi.mocked(researchHelper.performResearchQuery).mockResolvedValue("Consistent mock research.");
    vi.mocked(sequentialThinking.processWithSequentialThinking).mockResolvedValue(consistentMockRules);
    
    // Override writeFile to capture the path directly without explicit typing
    vi.mocked(fs.writeFile).mockImplementation((path, content, encoding) => {
      capturedFilePath = String(path);
      return Promise.resolve();
    });
    
    // Call the function under test with params object
    const params = { 
      productDescription, 
      userStories, 
      ruleCategories 
    };
    const result = await generateRules(params, mockConfig);
    
    // Snapshot assertion for the content
    expect(result).toMatchSnapshot('Rules Generator Output');
    
    // Verify file write was called
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
    
    // Verify file path was captured and contains expected components
    expect(capturedFilePath).toBeTruthy();
    expect(typeof capturedFilePath).toBe('string');
    expect(capturedFilePath.indexOf('rules-generator')).toBeGreaterThan(-1);
    expect(capturedFilePath.indexOf('.md')).toBeGreaterThan(-1);
  });
});
