// src/tools/task-list-generator/tests/index.test.ts
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generateTaskList } from '../index.js';
import { OpenRouterConfig } from '../../../types/workflow.js';
import * as researchHelper from '../../../utils/researchHelper.js';
import * as sequentialThinking from '../../sequential-thinking.js';
import fs from 'fs-extra';

// Mock dependencies
vi.mock('../../../utils/researchHelper.js');
vi.mock('../../sequential-thinking.js');
vi.mock('fs-extra');

describe('Task List Generator', () => {
  // Mock data and responses
  const mockConfig: OpenRouterConfig = {
    baseUrl: 'https://api.example.com',
    apiKey: 'test-api-key',
    geminiModel: 'google/gemini-2.5-pro-exp-03-25:free', 
    perplexityModel: 'perplexity/sonar-deep-research'
  };
  
  const mockProductDescription = "A project management tool with task tracking";
  const mockUserStories = 'US-001: As a user, I want to create tasks\nUS-002: As a user, I want to assign tasks';
  
  const mockResearchResults = [
    "Mock development lifecycle research data",
    "Mock task estimation research data",
    "Mock team structure research data"
  ];

  const mockGeneratedTaskList = "# Mock Task List\n\nThis is a mock task list generated by the test.";

  beforeEach(() => {
    // Clear all mocks before each test
    vi.clearAllMocks();
    
    // Mock initDirectories to avoid file system operations
    vi.spyOn(fs, 'ensureDir').mockResolvedValue();
    vi.spyOn(fs, 'writeFile').mockResolvedValue();
    
    // Mock the Promise.allSettled for research results
    vi.spyOn(Promise, 'allSettled').mockResolvedValue([
      { status: 'fulfilled', value: mockResearchResults[0] },
      { status: 'fulfilled', value: mockResearchResults[1] },
      { status: 'fulfilled', value: mockResearchResults[2] }
    ]);
    
    // Mock the performResearchQuery function
    vi.spyOn(researchHelper, 'performResearchQuery')
      .mockImplementation(async (query: string) => {
        // Return different results based on the query
        if (query.includes('lifecycle')) return mockResearchResults[0];
        if (query.includes('estimation')) return mockResearchResults[1];
        if (query.includes('team structure')) return mockResearchResults[2];
        return "Default mock research";
      });
    
    // Mock the processWithSequentialThinking function
    vi.spyOn(sequentialThinking, 'processWithSequentialThinking')
      .mockResolvedValue(mockGeneratedTaskList);
  });

  it('should perform research (Perplexity) then generation (Gemini) with research context', async () => {
    // Call the function under test
    await generateTaskList(mockProductDescription, mockUserStories, mockConfig);
    
    // Verify Perplexity research was called 3 times (for 3 different queries)
    expect(researchHelper.performResearchQuery).toHaveBeenCalledTimes(3);
    
    // Verify each research query contains appropriate context and uses the correct config
    const researchCalls = vi.mocked(researchHelper.performResearchQuery).mock.calls;
    expect(researchCalls[0][0]).toContain('lifecycle');
    expect(researchCalls[0][1]).toBe(mockConfig); // Should pass full config with perplexityModel
    expect(researchCalls[1][0]).toContain('estimation');
    expect(researchCalls[2][0]).toContain('team structure');
    
    // Verify Gemini generation was called exactly once
    expect(sequentialThinking.processWithSequentialThinking).toHaveBeenCalledTimes(1);
    
    // Get the generation prompt and verify it contains all inputs and research context
    const generationPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][0];
    expect(generationPrompt).toContain(mockProductDescription);
    expect(generationPrompt).toContain(mockUserStories);
    expect(generationPrompt).toContain("Pre-Generation Research Context");
    
    // Verify the config was correctly passed to processWithSequentialThinking
    const passedConfig = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][1];
    expect(passedConfig).toBe(mockConfig); // Should pass full config with geminiModel
    
    // Verify the system prompt was passed to guide Gemini in using research context
    const systemPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][2];
    expect(systemPrompt).toContain("Task List Generator");
    expect(systemPrompt).toContain("Using Research Context");
    
    // Verify results are written to file
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
  });

  it('should include product description in the research queries', async () => {
    const customProduct = "E-commerce website";
    await generateTaskList(customProduct, mockUserStories, mockConfig);
    
    // Verify the first and third research queries include the product description
    const firstQuery = vi.mocked(researchHelper.performResearchQuery).mock.calls[0][0];
    const thirdQuery = vi.mocked(researchHelper.performResearchQuery).mock.calls[2][0];
    
    expect(firstQuery).toContain(customProduct);
    expect(thirdQuery).toContain(customProduct);
  });

  it('should handle research failures gracefully', async () => {
    // Mock a failed research query
    vi.mocked(Promise.allSettled).mockResolvedValueOnce([
      { status: 'rejected', reason: new Error('Research failed') },
      { status: 'fulfilled', value: mockResearchResults[1] },
      { status: 'fulfilled', value: mockResearchResults[2] }
    ]);
    
    await generateTaskList(mockProductDescription, mockUserStories, mockConfig);
    
    // Verify Gemini generation was still called
    expect(sequentialThinking.processWithSequentialThinking).toHaveBeenCalledTimes(1);
    
    // Verify the prompt contains an error message for the failed research
    const generationPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][0];
    expect(generationPrompt).toContain("*Research on this topic failed*");
    
    // Verify results are still written to file
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
  });
});
