// src/tools/task-list-generator/tests/index.test.ts
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generateTaskList } from '../index.js';
import { OpenRouterConfig } from '../../../types/workflow.js';
import * as researchHelper from '../../../utils/researchHelper.js';
import * as sequentialThinking from '../../sequential-thinking.js';
import fs from 'fs-extra';

// Mock dependencies
vi.mock('../../../utils/researchHelper.js');
vi.mock('../../sequential-thinking.js');
vi.mock('fs-extra');

describe('Task List Generator', () => {
  // Mock data and responses
  const mockConfig: OpenRouterConfig = {
    baseUrl: 'https://api.example.com',
    apiKey: 'test-api-key',
    geminiModel: 'google/gemini-2.5-pro-exp-03-25:free', 
    perplexityModel: 'perplexity/sonar-deep-research'
  };
  
  const mockProductDescription = "A project management tool with task tracking";
  const mockUserStories = 'US-001: As a user, I want to create tasks\nUS-002: As a user, I want to assign tasks';
  
  const mockResearchResults = [
    "Mock development lifecycle research data",
    "Mock task estimation research data",
    "Mock team structure research data"
  ];

  const mockGeneratedTaskList = "# Mock Task List\n\nThis is a mock task list generated by the test.";

  beforeEach(() => {
    // Clear all mocks before each test
    vi.clearAllMocks();
    
    // Mock initDirectories to avoid file system operations
    vi.spyOn(fs, 'ensureDir').mockResolvedValue();
    vi.spyOn(fs, 'writeFile').mockResolvedValue();
    
    // Mock the Promise.allSettled for research results
    vi.spyOn(Promise, 'allSettled').mockResolvedValue([
      { status: 'fulfilled', value: mockResearchResults[0] },
      { status: 'fulfilled', value: mockResearchResults[1] },
      { status: 'fulfilled', value: mockResearchResults[2] }
    ]);
    
    // Mock the performResearchQuery function
    vi.spyOn(researchHelper, 'performResearchQuery')
      .mockImplementation(async (query: string) => {
        // Return different results based on the query
        if (query.includes('lifecycle')) return mockResearchResults[0];
        if (query.includes('estimation')) return mockResearchResults[1];
        if (query.includes('team structure')) return mockResearchResults[2];
        return "Default mock research";
      });
    
    // Mock the processWithSequentialThinking function
    vi.spyOn(sequentialThinking, 'processWithSequentialThinking')
      .mockResolvedValue(mockGeneratedTaskList);
  });

  it('should perform research (Perplexity) then generation (Gemini) with research context', async () => {
    // Call the function under test with params object
    const params = {
      productDescription: mockProductDescription,
      userStories: mockUserStories
    };
    await generateTaskList(params, mockConfig);
    
    // Verify Perplexity research was called 3 times (for 3 different queries)
    expect(researchHelper.performResearchQuery).toHaveBeenCalledTimes(3);
    
    // Verify each research query contains appropriate context and uses the correct config
    const researchCalls = vi.mocked(researchHelper.performResearchQuery).mock.calls;
    expect(researchCalls[0][0]).toContain('lifecycle');
    expect(researchCalls[0][1]).toBe(mockConfig); // Should pass full config with perplexityModel
    expect(researchCalls[1][0]).toContain('estimation');
    expect(researchCalls[2][0]).toContain('team structure');
    
    // Verify Gemini generation was called exactly once
    expect(sequentialThinking.processWithSequentialThinking).toHaveBeenCalledTimes(1);
    
    // Get the generation prompt and verify it contains all inputs and research context
    const generationPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][0];
    expect(generationPrompt).toContain(mockProductDescription);
    expect(generationPrompt).toContain(mockUserStories);
    expect(generationPrompt).toContain("Pre-Generation Research Context");
    
    // Verify the config was correctly passed to processWithSequentialThinking
    const passedConfig = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][1];
    expect(passedConfig).toBe(mockConfig); // Should pass full config with geminiModel
    
    // Verify the system prompt was passed to guide Gemini in using research context
    const systemPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][2];
    expect(systemPrompt).toContain("Task List Generator");
    expect(systemPrompt).toContain("Using Research Context");
    
    // Verify results are written to file
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
  });

  it('should include product description in the research queries', async () => {
    const customProduct = "E-commerce website";
    const params = {
      productDescription: customProduct,
      userStories: mockUserStories
    };
    await generateTaskList(params, mockConfig);
    
    // Verify the first and third research queries include the product description
    const firstQuery = vi.mocked(researchHelper.performResearchQuery).mock.calls[0][0];
    const thirdQuery = vi.mocked(researchHelper.performResearchQuery).mock.calls[2][0];
    
    expect(firstQuery).toContain(customProduct);
    expect(thirdQuery).toContain(customProduct);
  });

  it('should handle research failures gracefully', async () => {
    // Mock a failed research query
    vi.mocked(Promise.allSettled).mockResolvedValueOnce([
      { status: 'rejected', reason: new Error('Research failed') },
      { status: 'fulfilled', value: mockResearchResults[1] },
      { status: 'fulfilled', value: mockResearchResults[2] }
    ]);
    
    const params = {
      productDescription: mockProductDescription,
      userStories: mockUserStories
    };
    await generateTaskList(params, mockConfig);
    
    // Verify Gemini generation was still called
    expect(sequentialThinking.processWithSequentialThinking).toHaveBeenCalledTimes(1);
    
    // Verify the prompt contains an error message for the failed research
    const generationPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][0];
    expect(generationPrompt).toContain("*Research on this topic failed*");
    
    // Verify results are still written to file
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
  });

  // --- Snapshot Test ---
  it('should generate task list content matching snapshot', async () => {
    const productDescription = "A project tracking app";
    const userStories = `
US-101: As a user, I want to create task items
US-102: As a user, I want to assign tasks to team members
US-103: As a user, I want to track task progress
`;
    const consistentMockTaskList = `
## Phase: Project Setup
- **ID:** T-101
  **Title:** Initialize project repository
  *(Description):* Set up version control and project structure
  *(User Story):* US-101, US-102, US-103
  *(Priority):* High
  *(Dependencies):* None
  *(Est. Effort):* Small

## Phase: Backend Development
- **ID:** T-201
  **Title:** Create task model
  *(Description):* Define data structure for tasks
  *(User Story):* US-101
  *(Priority):* High
  *(Dependencies):* T-101
  *(Est. Effort):* Medium
`;

    // Variable to capture the file path argument directly
    let capturedFilePath = '';
    
    // Reset mocks with consistent values for snapshot stability
    vi.mocked(researchHelper.performResearchQuery).mockResolvedValue("Consistent mock research.");
    vi.mocked(sequentialThinking.processWithSequentialThinking).mockResolvedValue(consistentMockTaskList);
    
    // Override writeFile to capture the path directly without explicit typing
    vi.mocked(fs.writeFile).mockImplementation((path, content, encoding) => {
      capturedFilePath = String(path);
      return Promise.resolve();
    });
    
    // Call the function under test with params object
    const params = { 
      productDescription,
      userStories
    };
    const result = await generateTaskList(params, mockConfig);
    
    // Snapshot assertion for the content
    expect(result).toMatchSnapshot('Task List Generator Output');
    
    // Verify file write was called
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
    
    // Verify file path was captured and contains expected components
    expect(capturedFilePath).toBeTruthy();
    expect(typeof capturedFilePath).toBe('string');
    expect(capturedFilePath.indexOf('task-list-generator')).toBeGreaterThan(-1);
    expect(capturedFilePath.indexOf('.md')).toBeGreaterThan(-1);
  });
});
