// src/tools/prd-generator/tests/index.test.ts
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generatePRD } from '../index.js';
import { OpenRouterConfig } from '../../../types/workflow.js';
import * as researchHelper from '../../../utils/researchHelper.js';
import * as sequentialThinking from '../../sequential-thinking.js';
import fs from 'fs-extra';

// Mock dependencies
vi.mock('../../../utils/researchHelper.js');
vi.mock('../../sequential-thinking.js');
vi.mock('fs-extra');

describe('PRD Generator', () => {
  // Mock data and responses
  const mockConfig: OpenRouterConfig = {
    baseUrl: 'https://api.example.com',
    apiKey: 'test-api-key',
    geminiModel: 'google/gemini-2.5-pro-exp-03-25:free', 
    perplexityModel: 'perplexity/sonar-deep-research'
  };
  
  const mockResearchResults = [
    "Mock market analysis research data",
    "Mock user needs research data",
    "Mock industry standards research data"
  ];

  const mockGeneratedPRD = "# Mock PRD\n\nThis is a mock PRD generated by the test.";

  beforeEach(() => {
    // Clear all mocks before each test
    vi.clearAllMocks();
    
    // Mock initDirectories to avoid file system operations
    vi.spyOn(fs, 'ensureDir').mockResolvedValue();
    vi.spyOn(fs, 'writeFile').mockResolvedValue();
    
    // Mock the Promise.allSettled for research results
    vi.spyOn(Promise, 'allSettled').mockResolvedValue([
      { status: 'fulfilled', value: mockResearchResults[0] },
      { status: 'fulfilled', value: mockResearchResults[1] },
      { status: 'fulfilled', value: mockResearchResults[2] }
    ]);
    
    // Mock the performResearchQuery function
    vi.spyOn(researchHelper, 'performResearchQuery')
      .mockImplementation(async (query: string) => {
        // Return different results based on the query
        if (query.includes('market analysis')) return mockResearchResults[0];
        if (query.includes('user needs')) return mockResearchResults[1];
        if (query.includes('industry standards')) return mockResearchResults[2];
        return "Default mock research";
      });
    
    // Mock the processWithSequentialThinking function
    vi.spyOn(sequentialThinking, 'processWithSequentialThinking')
      .mockResolvedValue(mockGeneratedPRD);
  });

  it('should perform research (Perplexity) then generation (Gemini) with research context', async () => {
    // Test input
    const productDescription = "A test product description";
    
    // Call the function under test
    await generatePRD(productDescription, mockConfig);
    
    // Verify Perplexity research was called 3 times (for 3 different queries)
    expect(researchHelper.performResearchQuery).toHaveBeenCalledTimes(3);
    
    // Verify each research query contains appropriate context and uses the correct config
    const researchCalls = vi.mocked(researchHelper.performResearchQuery).mock.calls;
    expect(researchCalls[0][0]).toContain('market analysis');
    expect(researchCalls[0][1]).toBe(mockConfig); // Should pass full config with perplexityModel
    expect(researchCalls[1][0]).toContain('user needs');
    expect(researchCalls[2][0]).toContain('industry standards');
    
    // Verify Gemini generation was called exactly once
    expect(sequentialThinking.processWithSequentialThinking).toHaveBeenCalledTimes(1);
    
    // Get the generation prompt and verify it contains both product description and research context
    const generationPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][0];
    expect(generationPrompt).toContain(productDescription);
    expect(generationPrompt).toContain("Pre-Generation Research Context");
    
    // Verify the config was correctly passed to processWithSequentialThinking
    const passedConfig = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][1];
    expect(passedConfig).toBe(mockConfig); // Should pass full config with geminiModel
    
    // Verify results are written to file
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
  });

  it('should handle research failures gracefully', async () => {
    // Mock a failed research query
    vi.mocked(Promise.allSettled).mockResolvedValueOnce([
      { status: 'rejected', reason: new Error('Research failed') },
      { status: 'fulfilled', value: mockResearchResults[1] },
      { status: 'fulfilled', value: mockResearchResults[2] }
    ]);
    
    const productDescription = "A test product description";
    await generatePRD(productDescription, mockConfig);
    
    // Verify Gemini generation was still called
    expect(sequentialThinking.processWithSequentialThinking).toHaveBeenCalledTimes(1);
    
    // Verify the prompt contains an error message for the failed research
    const generationPrompt = vi.mocked(sequentialThinking.processWithSequentialThinking).mock.calls[0][0];
    expect(generationPrompt).toContain("*Research on this topic failed*");
    
    // Verify results are still written to file
    expect(fs.writeFile).toHaveBeenCalledTimes(1);
  });
});
