// src/tools/prd-generator/tests/index.test.ts
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'; // Ensure vi is imported
import { generatePRD, PRD_SYSTEM_PROMPT } from '../index.js';
import { OpenRouterConfig } from '../../../types/workflow.js';
import { CallToolResult } from '@modelcontextprotocol/sdk/types.js'; // Import CallToolResult
import * as researchHelper from '../../../utils/researchHelper.js';
import * as sequentialThinking from '../../sequential-thinking.js';
import { ApiError, AppError } from '../../../utils/errors.js'; // Import custom errors
import fs from 'fs-extra';
import logger from '../../../logger.js'; // Import logger

// Mock dependencies
vi.mock('../../../utils/researchHelper.js');
vi.mock('../../sequential-thinking.js');
vi.mock('fs-extra');
vi.mock('../../../logger.js'); // Mock logger

// Define helper variables for mocks (using 'as any' as a workaround for TS issues)
const mockPerformResearchQuery = researchHelper.performResearchQuery as any;
const mockProcessWithSeqThinking = sequentialThinking.processWithSequentialThinking as any;
const mockWriteFile = fs.writeFile as any;
const mockEnsureDir = fs.ensureDir as any;


describe('PRD Generator Tool Executor', () => {
  // Mock data and responses
  const mockConfig: OpenRouterConfig = {
    baseUrl: 'mock-url',
    apiKey: 'test-api-key',
    geminiModel: 'google/gemini-2.5-pro-exp-03-25:free',
    perplexityModel: 'perplexity/sonar-deep-research'
  };

  const mockResearchResults = [
    "Mock market analysis research data",
    "Mock user needs research data",
    "Mock industry standards research data"
  ];

  const mockGeneratedPRD = "# Mock PRD\n\nThis is a mock PRD generated by the test.";

  beforeEach(() => {
    // Reset mocks before each test
    vi.clearAllMocks();

    // Default mocks for successful execution
    mockEnsureDir.mockResolvedValue(undefined);
    mockWriteFile.mockResolvedValue(undefined);
    // Setup mock chain for research queries
    mockPerformResearchQuery
        .mockResolvedValueOnce(mockResearchResults[0]) // Market Analysis
        .mockResolvedValueOnce(mockResearchResults[1]) // User Needs
        .mockResolvedValueOnce(mockResearchResults[2]); // Standards
    mockProcessWithSeqThinking.mockResolvedValue(mockGeneratedPRD);
  });

   afterEach(() => {
       vi.restoreAllMocks();
   });

  it('should correctly assemble prompts, call dependencies, format result, and save file on success', async () => {
    const productDescription = "Fancy New Widget";
    const params = { productDescription };

    // Call the executor
    const result = await generatePRD(params, mockConfig);

    // 1. Verify Research Query Formulation
    expect(mockPerformResearchQuery).toHaveBeenCalledTimes(3);
    expect(mockPerformResearchQuery).toHaveBeenCalledWith(
        expect.stringContaining(`Market analysis and competitive landscape for: ${productDescription}`),
        mockConfig
    );
     expect(mockPerformResearchQuery).toHaveBeenCalledWith(
        expect.stringContaining(`User needs, demographics, and expectations for: ${productDescription}`),
        mockConfig
    );
     expect(mockPerformResearchQuery).toHaveBeenCalledWith(
        expect.stringContaining(`Industry standards, best practices, and common feature sets for products like: ${productDescription}`),
        mockConfig
    );

    // 2. Verify Main Prompt Assembly
    expect(mockProcessWithSeqThinking).toHaveBeenCalledTimes(1);
    const mainPromptArg = mockProcessWithSeqThinking.mock.calls[0][0];
    expect(mainPromptArg).toContain(productDescription);
    expect(mainPromptArg).toContain("## Pre-Generation Research Context");
    expect(mainPromptArg).toContain(mockResearchResults[0]);
    expect(mainPromptArg).toContain(mockResearchResults[1]);
    expect(mainPromptArg).toContain(mockResearchResults[2]);

    // 3. Verify System Prompt Usage
    const systemPromptArg = mockProcessWithSeqThinking.mock.calls[0][2];
    expect(systemPromptArg).toBe(PRD_SYSTEM_PROMPT); // Check exact system prompt

    // 4. Verify Result Formatting
    expect(result.isError).toBe(false);
    expect(result.content).toHaveLength(1);
    const resultText = result.content?.[0]?.text ?? '';
    expect(resultText).toMatch(/^# PRD: Fancy New Widget/); // Check title prefix (adjust if title logic changes)
    expect(resultText).toContain(mockGeneratedPRD);
    expect(resultText).toMatch(/_Generated: \d{1,2}\/\d{1,2}\/\d{4}, \d{1,2}:\d{2}:\d{2} (AM|PM)_$/); // Check timestamp format

    // 5. Verify File Saving
    expect(mockWriteFile).toHaveBeenCalledTimes(1);
    const writeFileArgs = mockWriteFile.mock.calls[0];
    expect(writeFileArgs[0]).toMatch(/workflow-agent-files[\\\/]prd-generator[\\\/].*fancy-new-widget.*-prd\.md$/); // Check path pattern
    expect(writeFileArgs[1]).toBe(resultText); // Check content saved
    expect(writeFileArgs[2]).toBe('utf8');
  });

  it('should include research failure messages in the main prompt', async () => {
    // Mock one research query to fail
    mockPerformResearchQuery.mockReset(); // Clear previous mocks
    mockPerformResearchQuery
        .mockRejectedValueOnce(new ApiError('Market research failed', 500)) // Market Analysis fails
        .mockResolvedValueOnce(mockResearchResults[1]) // User Needs succeeds
        .mockResolvedValueOnce(mockResearchResults[2]); // Standards succeeds

    const productDescription = "Widget With Failing Research";
    await generatePRD({ productDescription }, mockConfig);

    // Verify generation was still called
    expect(mockProcessWithSeqThinking).toHaveBeenCalledTimes(1);

    // Verify the prompt contains the failure message for the first query
    const mainPromptArg = mockProcessWithSeqThinking.mock.calls[0][0];
    expect(mainPromptArg).toContain("### Market Analysis:\n*Research on this topic failed.*\n\n");
    // Verify it still contains the successful results
    expect(mainPromptArg).toContain(mockResearchResults[1]);
    expect(mainPromptArg).toContain(mockResearchResults[2]);
  });

  it('should return error CallToolResult if research query throws unexpected error', async () => {
      const researchError = new Error("Unexpected research issue");
      mockPerformResearchQuery.mockRejectedValueOnce(researchError); // Throw generic error

      const productDescription = "Error Prone Widget";
      const result = await generatePRD({ productDescription }, mockConfig);

      expect(result.isError).toBe(true);
      expect(result.content?.[0]?.text).toContain('Error generating PRD');
      expect(result.content?.[0]?.text).toContain(researchError.message);
      expect(mockProcessWithSeqThinking).not.toHaveBeenCalled(); // Generation shouldn't run
      expect(mockWriteFile).not.toHaveBeenCalled(); // File shouldn't be saved
  });

   it('should return error CallToolResult if sequential thinking throws error', async () => {
       const seqThinkingError = new AppError("Sequential thinking failed");
       mockProcessWithSeqThinking.mockRejectedValueOnce(seqThinkingError); // Throw error

       const productDescription = "Confusing Widget";
       const result = await generatePRD({ productDescription }, mockConfig);

       expect(result.isError).toBe(true);
       expect(result.content?.[0]?.text).toContain('Error generating PRD');
       expect(result.content?.[0]?.text).toContain(seqThinkingError.message);
       expect(mockPerformResearchQuery).toHaveBeenCalledTimes(3); // Research should have run
       expect(mockWriteFile).not.toHaveBeenCalled(); // File shouldn't be saved
   });

   // Optional: Test case where fs.writeFile fails (though current impl doesn't make it a hard error)
   it('should return success CallToolResult but log error if file writing fails', async () => {
       const fileWriteError = new Error("Disk full");
       mockWriteFile.mockRejectedValueOnce(fileWriteError);

       const productDescription = "Unsavable Widget";
       const result = await generatePRD({ productDescription }, mockConfig);

       // Current implementation catches fs errors but still returns success content
       expect(result.isError).toBe(false);
       expect(result.content?.[0]?.text).toContain(mockGeneratedPRD);
       expect(logger.error).toHaveBeenCalledWith(expect.objectContaining({ err: fileWriteError }), 'PRD Generator Error');
  });

  // --- Snapshot Test ---
  it('should generate PRD content matching snapshot', async () => {
      const productDescription = "A sample product for snapshot";
      const params = { productDescription };
      const consistentMockPRD = "## Section 1\nDetails...\n## Section 2\nMore details...";

      // Variable to capture the path argument - explicitly typed as string
      let capturedFilePath: string = '';

      // Reset mocks and set custom implementation to capture arguments directly
      mockPerformResearchQuery.mockReset();
      mockPerformResearchQuery.mockResolvedValue("Consistent mock research.");
      mockProcessWithSeqThinking.mockReset();
      mockProcessWithSeqThinking.mockResolvedValue(consistentMockPRD);
      
      // Override mockWriteFile to capture the path argument directly
      mockWriteFile.mockImplementation((path: string, content: any, encoding: string) => {
          // Explicitly ensure path is treated as a string
          capturedFilePath = String(path);
          return Promise.resolve();
      });

      // Call the executor
      const result = await generatePRD(params, mockConfig);

      expect(result.isError).toBe(false);
      expect(result.content).toHaveLength(1);
      const resultText = result.content?.[0]?.text ?? '';

      // Instead of using string methods that might cause TS issues, 
      // let's directly snapshot the original content
      // Note: This means timestamps will be included in the snapshot
      const contentToSnapshot = resultText || '';

      // Snapshot assertion for the content - with a descriptive name
      expect(contentToSnapshot).toMatchSnapshot('PRD Generator Output');

      // Verification of the file write being called
      expect(mockWriteFile).toHaveBeenCalledTimes(1);
      
      // Verify that the path was captured without using string methods that might cause TS issues
      expect(capturedFilePath).toBeTruthy();
      
      // Instead of normalization and regex, check for expected substrings in the path
      expect(capturedFilePath.indexOf('workflow-agent-files')).toBeGreaterThan(-1);
      expect(capturedFilePath.indexOf('prd-generator')).toBeGreaterThan(-1);
      expect(capturedFilePath.indexOf('a-sample-product-for-snapsho')).toBeGreaterThan(-1);
      expect(capturedFilePath.indexOf('.md')).toBeGreaterThan(-1);
  });
});
