name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    strategy:
      matrix:
        node-version: [20.x]
      fail-fast: false

    env:
      CI: true
      NODE_ENV: test
      CI_SAFE_MODE: true
      FORCE_REAL_LLM_CONFIG: false
      OPTIMIZE_FOR_CI: true
      OPENROUTER_API_KEY: ci-test-key-safe-vitest
      OPENROUTER_BASE_URL: https://test.openrouter.ai/api/v1
      GEMINI_MODEL: google/gemini-2.5-flash-preview-05-20
      PERPLEXITY_MODEL: perplexity/llama-3.1-sonar-small-128k-online

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        timeout-minutes: 5

      - name: Build
        run: npm run build
        timeout-minutes: 5

      - name: Lint
        run: npm run lint
        timeout-minutes: 3

      - name: Run CI-safe tests (no live LLM calls)
        run: npm run test:ci-safe -- --reporter=json --maxConcurrency=8
        timeout-minutes: 15

      # E2E tests excluded from CI/CD - they require live LLM calls
      # Run manually with: npm run test:e2e:real
      # - name: Run end-to-end tests
      #   run: npm run test:e2e

      - name: Generate coverage report
        run: npm run coverage
        timeout-minutes: 10

      - name: Ensure output directories exist
        run: |
          mkdir -p coverage
          mkdir -p test-results
        if: always()

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-${{ matrix.node-version }}
          path: coverage/
          if-no-files-found: warn
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.node-version }}
          path: test-results/
          if-no-files-found: warn
          retention-days: 7
